version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: eventgo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: eventgo
    ports:
      - "5448:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
